# Generated by Django 2.2.11 on 2020-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0023_payawardresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningnode',
            name='qos_score',
            field=models.FloatField(default=-1, verbose_name='Higher score means higher quality of service. Expected range is 0.0 to -100.0'),
        ),
    ]
